#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

extpg_connect_cmd() {
    local cmd="extpg:connect"
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    set -- $cmd $@

    local cluster="default"
    local db="$2"
    extpg_psql "$cluster" "$db"
}

extpg_connect_cmd "$@"