#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

extpg_dump_cmd() {
    local cmd="extpg:dump"
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    set -- $cmd $@

    local cluster="default"
    local db="$2"
    extpg_pg_dump "$cluster" "$db"
}

extpg_dump_cmd "$@"