#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

extpg_link_cmd() {
    local cmd="extpg:link"
    # Support --app/$DOKKU_APP_NAME flag
    # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
    set -- $cmd $@
    ##

    [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
    local app="$2";  verify_app_name "$2"
    local database="$3"
    local cluster="default"

    extpg_link "$cluster" "$database" "$app"
}

extpg_link_cmd "$@"
