#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

extpg_run_cmd() {
    local cmd="extpg:run"
    local argv=("$@")
    [[ ${argv[0]} == "$cmd" ]] && shift 1
    set -- $cmd $@

    local cluster="default"
    local db="$2"
    shift 2
    extpg_sql "$cluster" "$db" "$*"
}

extpg_run_cmd "$@"